export const ADD_PATIENT = 'ADD_PATIENT';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const VIEW_DETAILS = 'VIEW_DETAILS';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';